
server:
  port: 8010
  servlet:
    context-path: /nowcoder


spring:
  application:
    #    应用的名称，可选
    name: nowcoder
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/nowcode?serverTimezone=UTC
      username: root
      password: 123456
  thymeleaf:
    cache: false
# MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    username: 1478598523@qq.com
    password: ENC(vnSna49/jRqOXK58Hno0EPGDsV3hUAN7XbXqY9nF0D1Uit8ZIMlziZ06WRipRNc6hbMdX1apJospktQS9xOLog==)
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true




mybatis:
  #设置type搜索包的路径
  type-aliases-package: com.fct.nowcoder.entity
  #设置mapper的扫描
  mapper-locations: classpath:mapper/*.xml

#jasypt加密
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: gsdagh

#配置域名，当用户注册时可链接到网站
nowcoder:
  path: http://127.0.0.1:8010
  upload: D:\\project/javaProject/images